config/routes.rb
DemoApp::Application.routes.draw do

  match '/home', to: 'landing_pages#home'

  match '/renters', to:'landing_pages#renters'

  match '/owners', to:'landing_pages#owners'

  match '/how', to:'landing_pages#how'

  match '/about', to:'landing_pages#about'
  

  resources :offices

  root :to => 'landing_pages#home'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :description, :headline, :location, :image, :user_id

  belongs_to :user
  
  mount_uploader :image, ImageUploader

  validates :headline, :length => { :maximum => 140 }

  validates :description, :length => { :maximum => 255 }

end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :availability, :company_name, :company_desc, :company_url, :contact_email, :contact_name, :contact_phone,
                  :contact_picture, :description, :image1, :image2, :image3, :image4, :insurance, :rent, :size, :swap,
                  :title, :years, :accomodate, :available, :loc_zip, :loc_addr1, :loc_addr2, :loc_city, :loc_state,
                  :features, :on_site
  validates(:title, presence: true)
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:contact_email, presence: true, format: { with: VALID_EMAIL_REGEX })
  mount_uploader :image1, ImageUploader
  mount_uploader :contact_picture, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :phone
  has_many :listing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
  end

  def about
  end

  def renters
  end

  def owners
  end

  def how
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        # send email to user and us on successful listing create
        OfficeMailer.add_listing_confirm(@office).deliver

        format.html { redirect_to @office, notice: 'Studio was successfully created.' }
        format.json { render json: @office, status: :created, location: @office }
      else
        format.html { render action: "new" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        # send email to us on successful listing edit
        OfficeMailer.edit_listing_confirm(@office).deliver

        format.html { redirect_to @office, notice: 'Studio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing_pages/about.html.erb
<div class="container">
      <h2>About Us</h2>
      <p>Tradewinz is a free offering from Intuit Labs. We're passionate about helping small businesses succeed.
        By enabling trusted connections, we're helping entrepreneurs unite to share resources and know-how for mutual benefit.
      </p>
      <h2>Contact Us</h2>
      <p>
        Questions or feedback? Send us a note at
        <a href="mailto:tradewinz@intuit.com?subject=Feedback" class="btn-link">tradewinz@intuit.com</a>
      </p>
</div>

app/views/landing_pages/home.html.erb
<div class="container">
  <div class="row" style="background-color: #ada28b; margin-right: -20px; padding-bottom: 20px;">
    <div class="span12">
      <h1>Save money on your next photo shoot</h1>
    </div>

    <div class="span6">
      <%= image_tag("studio-home.png", class: "img-polaroid", alt: "studio rental") %>
    </div>

    <div class="span6" style="text-align:center; background-color: #b5ab97; border: 1px solid #c6beae; height: 300px;">
      <h3 style="margin-top: 60px;">Find your dream studio at a price you can <br>afford. Share with a local photographer. </h3>

      <div class="span4 offset1" style="margin-top:20px">
        <a href="<%= offices_path %>" style="text-decoration:none;">
          <button class="btn btn-large btn-primary btn-call-to-action input-block-level" id="seeListingBtn">
            See Listings </button>
        </a>
      </div>

    </div>
  </div>

  <div class="row" style="padding-top:10px; background-color: #ffffff; margin-right: -20px; padding-bottom:   40px;">
    <div class="span12">
      <h2>Why search on Tradewinz?</h2>
    </div>

    <div class="row" style="margin-left: 0;">
      <div class="span6">
        <div class="row">
          <div class="span1"> <%= image_tag("icon-free.png", alt: "icon free") %></div>
          <div class="span5">
            <h4>No fees</h4>
            We are doing this to support small businesses in the USA. We succeed when you succeed.
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="row">
          <div class="span1"> <%= image_tag("icon-quality.png", alt: "icon screen") %>
          </div>
          <div class="span5">
            <h4>Premium quality</h4>
            Enjoy a premium studio without the premium price of a commercial rental. Our listings are from photographers
            who have "extra" space.
          </div>
        </div>
      </div>
    </div>

    <div class="row" style="margin-top: 24px; margin-left: 0;">
      <div class="span6">
        <div class="row">
          <div class="span1"> <%= image_tag("icon-trusted.png", alt: "icon free") %>
          </div>
          <div class="span5">
            <h4>Trusted brand</h4>
            From the makers of Quickbooks and Turbo Tax - over 6M small businesses trust us to help with their finances.
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="row">
          <div class="span1"> <%= image_tag("icon-unite.png", alt: "icon free") %>
          </div>
          <div class="span5">
            <h4>Photographers unite - locally</h4>
            We're connecting local photographers who are serious about their business and reliable to work with.

          </div>
        </div>
      </div>
    </div>
  </div>

</div> <!-- /container -->

<!-- Modal -->
<div id="rentModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="rentModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="rentModalLabel">Studio Rental Guide</h3>
  </div>
  <div class="modal-body">
    <p>Find below the average rentals in different cities:</p>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>New York</th>
        <th>Los Angeles</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>$55 - $75 an hour</td>
        <td>$35 - $60 an hour</td>
      </tr>
      <tr>
        <td>$200 - $300 /half day (4-5 hrs) </td>
        <td>$200 - $250 /half day (4-5 hrs)</td>
      </tr>
      <tr>
        <td>$400 - $900 /full day (8-12 hrs) </td>
        <td>$450 – $600 /full day (8-12 hrs) </td>
      </tr>
      </tbody>
    </table>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Chicago</th>
        <th>San Francisco</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>$55 - $75 an hour</td>
        <td>$35 - $60 an hour</td>
      </tr>
      <tr>
        <td>$200 - $300 /half day (4-5 hrs) </td>
        <td>$200 - $250 /half day (4-5 hrs)</td>
      </tr>
      <tr>
        <td>$400 - $900 /full day (8-12 hrs) </td>
        <td>$450 – $600 /full day (8-12 hrs) </td>
      </tr>
      </tbody>
    </table>
    <p> Providing the following amenities may increase your rental rates:</p>
    <ul>
      <li>Location – downtowns, with their easy access via public transport, are more expensive than suburbs.</li>
      <li>Equipment + accessories – Studio rentals that come with lights, umbrellas, veils, accessories and other specialized equipment rentals cost more.</li>
      <li>Higher ceiling.</li>
      <li>Freight elevators</li>
      <li>Basic refreshments and water</li>
      <li>Separate make-up room, dressing room and waiting areas.</li>
      <li>Storage</li>
    </ul>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/landing_pages/how.html.erb
<div class="container" xmlns="http://www.w3.org/1999/html">
  <h2>How It Works</h2>

  <h3>If you have work space to share</h3>
  <br>

  <ol>
    <li>Create your listing on tradewinz.  The more love you put into the listing, the more business you’ll get.
      Contact us if you need help. </li>
    <br>

    <li>You’ll get an email notification when someone expresses interest in your listing.
      We’ll tell you if they meet your requirements, or we can follow up on any specific concerns you have.
      On a weekly basis, we’ll send you a report on how many people reviewed your listing.  </li>
    <br>

    <li>Tell us which applicants may contact you.  You’re in charge of who can use your space,
      and we won’t release your contact information until you give us approval. We’ll save you from spammers!   </li>
    <br>

    <li>Communicate with the applicant to finalize the rental agreement (or swap arrangement).
      Make sure you discuss rules for what’s on or off limits in the your space.
      We’re here to help you if you have questions.  </li>
    <br>

    <li>Enjoy the extra cash you just made!  </li>
    <br>

  </ol>

  <h3>If you need work space</h3>
  <br>

  <ol>
    <li>Review the listings available on tradewinz.
      Check out the description and host profile to see if they match what you’re looking for. </li>
    <br>
    <li>Select and submit the listings you’re interested in.
      You can also ask any questions you want us to share with the host.   </li>
    <br>
    <li>You’ll get an email notification as soon as we’ve heard from the host.   We’ll consolidate all the answers
      to your questions, saving you time.  If the host does not feel that he/she can accommodate your request,
      we’ll let you know  </li>
    <br>
    <li>Contact the host(s) who are excited to talk to you and won’t waste your time.
      We won’t share your contact information until they tell us they’re interested.
      Finalize the rental agreement (or swap arrangement).
      Make sure you know how to get into the space and how to work any equipment provided.  </li>
    <br>
    <li>Get your work done in the space you need – and pocket the savings you made by working with another
      local entrepreneur vs. a commercial property. </li>
    <br>
  </ol>
  <br>
  <h4>Do us a kindness and tell us how your experience was, so we can make improvements.
    And even better – tell your friends and colleagues! </h4>
  <br>
</div>

app/views/landing_pages/owners.html.erb

<div class="container">      
  <div class="row" style="background-color: #ada28b; margin-right: -20px; padding-bottom: 20px;">      
    <div class="span12">
      <h1>Turn extra studio space into extra income</h1>
    </div>

    <div class="span6">
      <%= image_tag("studio-host.png", class: "img-polaroid", alt: "studio rental") %>
    </div>
  
    <div class="span6" style="text-align:center; background-color: #b5ab97; border: 1px solid #c6beae; height: 300px;">
      <h3 style="margin-top: 60px;">You provide the studio. <br>
        We do the work. </h3>

      <div class="span4 offset1" style="margin-top:20px">
        <a href="<%= new_office_path%>" style="text-decoration:none;">
          <button class="btn btn-large btn-primary btn-call-to-action input-block-level" id="newListingBtn"> Add Listing </button>
        </a>
      </div>
      <div class="row">
        <div class="span6" style="margin-top: 10px;">See <a style="color: #000000; text-decoration: underline;" href="#rentModal" data-toggle="modal">how much</a> you can earn.</div>
      </div> 
    </div> 
  </div>

  <div class="row" style="padding-top:10px; background-color: #ffffff; margin-right: -20px; padding-bottom:   40px;">
    <div class="span12">
      <h2>Why list your studio on Tradewinz?</h2>
    </div>

    <div class="row" style="margin-left: 0;">
      <div class="span6">
        <div class="row">
          <div class="span1"> <%= image_tag("icon-free.png", alt: "icon free") %></div>
            <div class="span5">
              <h4>No listing or membership fees</h4>
              You get 100% of the rent. We are doing this to support small businesses in the USA. We succeed when you succeed.
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="row">
            <div class="span1"> <%= image_tag("icon-screen.png", alt: "icon screen") %>
            </div>
            <div class="span5">
              <h4>Get pre-screened applicants</h4>
                We recruit and screen local, reliable applicants for you, many of whom are like-minded entrepreneurs you may enjoy meeting.
            </div>
          </div>
        </div> 
      </div>

      <div class="row" style="margin-top: 24px; margin-left: 0;">
        <div class="span6">
          <div class="row">
            <div class="span1"> <%= image_tag("icon-trusted.png", alt: "icon free") %>
            </div>
            <div class="span5">
              <h4>Trusted brand</h4>
              From the makers of Quickbooks and Turbo Tax - over 6M small businesses trust us to help with their finances.
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="row">
            <div class="span1"> <%= image_tag("icon-spam.png", alt: "icon free") %>
            </div>
            <div class="span5">
              <h4>No spam</h4>
              Your contact information is private, you approve who can see it. You'll also get metrics to track how much interest your listing generates.
            </div>
          </div>
        </div>
      </div> 
    </div>
  
</div> <!-- /container -->

<!-- Modal -->
<div id="rentModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="rentModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="rentModalLabel">Studio Rental Guide</h3>
  </div>
  <div class="modal-body">
    <p>Find below the average rentals in different cities:</p>
    <table class="table table-striped">  
           <thead>  
             <tr>  
               <th>New York</th>  
               <th>Los Angeles</th> 
             </tr>  
           </thead>  
           <tbody>  
             <tr>  
               <td>$55 - $75 an hour</td>  
          <td>$35 - $60 an hour</td>  
             </tr>  
             <tr>  
               <td>$200 - $300 /half day (4-5 hrs) </td>   
               <td>$200 - $250 /half day (4-5 hrs)</td>  
             </tr>  
             <tr>  
               <td>$400 - $900 /full day (8-12 hrs) </td> 
               <td>$450 – $600 /full day (8-12 hrs) </td>   
             </tr>  
           </tbody>  
    </table>
    <table class="table table-striped">  
           <thead>  
             <tr>  
               <th>Chicago</th>  
               <th>San Francisco</th> 
             </tr>  
           </thead>  
           <tbody>  
             <tr>  
               <td>$55 - $75 an hour</td>  
          <td>$35 - $60 an hour</td>  
             </tr>  
             <tr>  
               <td>$200 - $300 /half day (4-5 hrs) </td>   
               <td>$200 - $250 /half day (4-5 hrs)</td>  
             </tr>  
             <tr>  
               <td>$400 - $900 /full day (8-12 hrs) </td> 
               <td>$450 – $600 /full day (8-12 hrs) </td>   
             </tr>  
           </tbody>  
    </table>
    <p> Providing the following amenities may increase your rental rates:</p>
    <ul>
       <li>Location – downtowns, with their easy access via public transport, are more expensive than suburbs.</li>
       <li>Equipment + accessories – Studio rentals that come with lights, umbrellas, veils, accessories and other specialized equipment rentals cost more.</li>
      <li>Higher ceiling.</li>
      <li>Freight elevators</li>
      <li>Basic refreshments and water</li>
      <li>Separate make-up room, dressing room and waiting areas.</li>
      <li>Storage</li>
       
    </ul>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta name="description" content="Tradewinz facilitates photo studio rental and sharing between photographers.
   We help photographers with studios make extra money by renting out their excess studio space and equipments.
   We help other photographers rent a photo studio cheaply for short or long term needs and work together with studio owners.">

   <meta name="keywords" content="Tradewinz, Tradewinz studio, Tradewinz photo studio,
   rent exchange share photo photography photo studio photography studio photography studio rental photo studio rental portrait studio rental photography studio for rent,
   rental photo studio,
   photography studio renting,
   photography lighting and equipment rentals studio lighting rental dressing room rental client area rental,
   background rental automotive photography"/>

   <meta name="author" content="Intuit Labs">

  <title>Photo Studio Rental and Sharing by Photographers</title>

  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

<body>
<div class = "container">
	<div class="row" style="height: 60px; margin-right: -20px;">
    <div class="span12">
            <ul class="nav nav-pills pull-right">
                <li><%= link_to "Home", home_path %></li>
                <li><%= link_to "Listings", offices_path %> </li>
                <li><%= link_to "List Your Studio", owners_path%> </li>
                <li><%= link_to "How It Works", how_path %></li>
                <li><%= link_to "About Us", about_path %> </li>
            </ul>
            <a href="/home">
                <h3 class="muted" style="margin-top: 12px;">
                  <%= image_tag("logo.png", alt: "tradewinz logo") %>
                </h3>
            </a>
    </div>
  </div> 

  <%= yield %>

	<!--div class="footer">
      <p>&copy; Intuit, Inc. All rights reserved
        <a href="http://security.intuit.com/privacy/">Privacy Policy</a>
      </p>

	</div-->

  <div class="row" style="border-top: 4px solid #fabb0f; margin-right: -20px;">
    <div class="span12" style="margin-bottom: 30px; padding-top: 24px;">
      <p>© Intuit, Inc. All rights reserved
        <a href="http://security.intuit.com/privacy/">Privacy Policy</a>
      </p>
    </div>
  </div>



</div>

<!-- begin Google Analytics code -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38308750-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<!-- end GA code -->

<!-- begin SnapEngage code -->
<script type="text/javascript">
    (function() {
        var se = document.createElement('script'); se.type = 'text/javascript'; se.async = true;
        se.src = '//commondatastorage.googleapis.com/code.snapengage.com/js/c441023c-0525-4d13-bf03-eaaaedc44080.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(se, s);
    })();
</script>
<!-- end SnapEngage code -->

<!-- jQquery validation -->
<script type="text/javascript">
    $("#saveListingBtn").click(function() {
        $("#new_office").validate({
            rules: {
                "office[contact_email]": {required: true, email: true},
                "office[title]": {required: true}
            },
            messages: {
                "office[contact_email]": "Please provide a valid email",
                "office[title]": "Please provide a title for your listing"
            },
            errorPlacement: function(error, element) {
                element.after(error);
                element.css('border', 'solid red 2px');
            }
        });
        _gaq.push(['_trackEvent', 'SaveListing', 'User saves a listing']);
    });

    $("#newListingBtn").click(function() {
        _gaq.push(['_trackEvent', 'NewListing', 'User clicks on Add Listing']);
    });

    $("#seeListingBtn").click(function() {
        _gaq.push(['_trackEvent', 'SeeListings', 'User clicks on See Listing']);
    });

</script>


</body>


</html>

app/views/offices/edit.html.erb
<h2>Update Listing</h2>

<%= render 'form' %>

<br>
<%= link_to "View all listings", offices_path, class: "btn btn-medium" %>
<br><br>

app/views/offices/index.html.erb
<h2>All Listings</h2>
<div class="row">
    <div id="offices" class="span12">

    <% @offices.each do |office| %>

      <div class="row search_result">

        <div class="span2" style="padding: 4px; border: 1px solid #D0D0D0;
                vertical-align: middle; text-align: center; background-color: #FFFFFF;">
            <a href= "<%= office_path(office)  %>" >
                <%= image_tag office.image1_url(:small).to_s, :size=> "130x100", :alt=> "Photo" %>
            </a>
        </div>

        <div class="span6">
            <%= link_to office.title, office %>
        </div>

        <div class="span3">
          <%= office.loc_city %>, <%= office.loc_state %>
        </div>

      </div>

    <% end %>
    </div>
  <br>
</div>

app/views/offices/show.html.erb
<h2 id="notice"><%= notice %></h2>

<p>
  <b>Title : </b>
  <%= @office.title %>
</p>

<p>
  <b>Size : </b>
  <%= @office.size %> sq.ft.
</p>

<p>
  <b>Location City : </b>
  <%= @office.loc_city %>
</p>

<p>
  <b>Location State : </b>
  <%= @office.loc_state %>
</p>


<p>
  <b>Accommodates : </b>
  <%= @office.accomodate %>
</p>

<p>
  <b>Description : </b>
  <%= @office.description.gsub("\n", "<br>").html_safe %>
</p>


<p>
  <b>Rent and Availability : </b>
  <%= @office.available.gsub("\n", "<br>").html_safe %>
</p>


<p>
  <b>Photo : </b>
  <%= image_tag @office.image1_url.to_s, alt: "Photo" %>
</p>

<p>
  <b>Require Liability Insurance : </b>
  <% if @office.insurance %>Yes
  <% else %>No
  <% end %>
</p>

<p>
  <b>Someone On-Site : </b>
  <% if @office.on_site %>Yes
  <% else %>No
  <% end %>

</p>

<p>
  <b>Swap OK : </b>
  <% if @office.swap %>Yes
  <% else %>No
  <% end %>

</p>

<p>
  <b>Company name : </b>
  <%= @office.company_name %>
</p>

<p>
  <b>Years in business : </b>
  <%= @office.years %>
</p>

<p>
  <b>Owner description : </b>
  <%= @office.company_desc.gsub("\n", "<br>").html_safe %>
</p>

<p>
  <b>Company website : </b>
  <%= @office.company_url %>
</p>


<br>

<h4>If you are interested in renting this space, please email us at
   <a href="mailto:tradewinz@intuit.com?subject=Interested in renting?" class="btn-link">tradewinz@intuit.com</a> with details about your needs.
</h4>

<br>
<%= link_to "Show all listings", offices_path, class: "btn btn-medium" %>
<br><br>